### PR TITLE
Prometheans melt on death, and can now be revived.

### PR DESCRIPTION
**Pull request by fludd12**
Prometheans will now properly melt into a puddle upon death again.

However, in exchange, they can now be more easily revived, without giving them heavy cloning sickness! Simply inject their core with 40u of phoron, and they'll come back. They may need a few moments to grow back fully, though.

Up for changing anything as needed!
Same branch and such as https://github.com/VOREStation/VOREStation/pull/3750 for synchronicity.

### CODE REVIEW

**Comment by fludd12** [comment]
OHGOD SORRY

**Comment by drexample** [comment]
WHO DARES TO DISTURB MY SLUMBER?!

**Comment by fludd12** [comment]
I broke everything whoops
Let me actually figure out how to fork this without github trying to consume my trachea

**Comment by drexample** [comment]
You’re in the wrong repo, kid @fludd12

**Comment by drexample** [comment]
Go to chatter’s. I no longer maintain the repo.

**Comment by drexample** [comment]
You die or you die, man. 
You either die or you die.

**Pull request closed without merging**
